/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student.management;
import java.awt.*;
import java.sql.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.*;
/**
 *
 * @author agampreetsingh
 */
public class main extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(main.class.getName());
    private TableRowSorter<DefaultTableModel> sorter;
    
    public main() {
        initComponents();
        setupTableSorter();
        loadStudentData();
    }
    
    String[] columnNames = {"Class", "Roll No", "First Name", "Last Name", "Date of Birth", "Gender"};
    DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
           return false;
        }
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        panelStudents = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        studentsTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        filterLabel = new javax.swing.JLabel();
        filterCombo = new javax.swing.JComboBox<>();
        clearButton = new javax.swing.JButton();
        allLabel = new javax.swing.JLabel();
        panelAddDel = new javax.swing.JPanel();
        addStudentLabel = new javax.swing.JLabel();
        classLabel = new javax.swing.JLabel();
        rollNoLabel = new javax.swing.JLabel();
        fnameLabel = new javax.swing.JLabel();
        lnameLabel = new javax.swing.JLabel();
        dobLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        deleteStudentLabel = new javax.swing.JLabel();
        deleteClassLabel = new javax.swing.JLabel();
        deleteRollNoLabel = new javax.swing.JLabel();
        rollNoField = new javax.swing.JTextField();
        fnameField = new javax.swing.JTextField();
        dobField = new javax.swing.JTextField();
        lnameField = new javax.swing.JTextField();
        deleteRollNoField = new javax.swing.JTextField();
        classComboAdd = new javax.swing.JComboBox<>();
        genderCombo = new javax.swing.JComboBox<>();
        classComboDelete = new javax.swing.JComboBox<>();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        addDelLabel = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jSeparator2 = new javax.swing.JSeparator();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        panelEdit = new javax.swing.JPanel();
        editRollNoLabel = new javax.swing.JLabel();
        editFnameLabel = new javax.swing.JLabel();
        editLnameLabel = new javax.swing.JLabel();
        editDobLabel = new javax.swing.JLabel();
        editGenderLabel = new javax.swing.JLabel();
        editRollNoField = new javax.swing.JTextField();
        editFnameField = new javax.swing.JTextField();
        editLnameField = new javax.swing.JTextField();
        editDobField = new javax.swing.JTextField();
        editGenderCombo = new javax.swing.JComboBox<>();
        editClassCombo = new javax.swing.JComboBox<>();
        updateButton = new javax.swing.JButton();
        editLabel = new javax.swing.JLabel();
        editClassLabel1 = new javax.swing.JLabel();
        requiredLabel2 = new javax.swing.JLabel();
        requiredLabel1 = new javax.swing.JLabel();
        jbtPanelStudents = new javax.swing.JButton();
        jbtPanelAddDel = new javax.swing.JButton();
        jbtPanelEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Helvetica Neue", 1, 40)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Student Management System");
        title.setAlignmentY(0.0F);

        mainPanel.setLayout(new java.awt.CardLayout());

        panelStudents.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studentsTable.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        studentsTable.setModel(tableModel);
        scrollPane.setViewportView(studentsTable);

        panelStudents.add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 135, 899, 365));

        searchLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        searchLabel.setText("Search:");

        searchField.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
        });

        filterLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        filterLabel.setText("Class");

        filterCombo.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        filterCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "11", "12" }));
        filterCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterComboActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(clearButton)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {clearButton, filterCombo});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(filterLabel)
                        .addComponent(filterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchLabel)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(clearButton)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {clearButton, filterCombo, filterLabel, searchField, searchLabel});

        panelStudents.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 87, 899, -1));

        allLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        allLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        allLabel.setText("All Students");
        allLabel.setAlignmentY(0.0F);
        panelStudents.add(allLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 893, 81));

        mainPanel.add(panelStudents, "panelStudents");

        addStudentLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        addStudentLabel.setText("Add Student:");

        classLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        classLabel.setText("Class:");

        rollNoLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        rollNoLabel.setText("Roll No.:");

        fnameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        fnameLabel.setText("First Name:");

        lnameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lnameLabel.setText("Last Name:");

        dobLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        dobLabel.setText("DOB (YYYY-MM-DD)");

        genderLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        genderLabel.setText("Gender");

        deleteStudentLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        deleteStudentLabel.setText("Delete Student");

        deleteClassLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        deleteClassLabel.setText("Class");

        deleteRollNoLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        deleteRollNoLabel.setText("Roll No.");

        rollNoField.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        rollNoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollNoFieldActionPerformed(evt);
            }
        });

        fnameField.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        dobField.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        lnameField.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        deleteRollNoField.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        deleteRollNoField.setAlignmentX(0.0F);
        deleteRollNoField.setAlignmentY(0.0F);

        classComboAdd.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        classComboAdd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "11", "12" }));

        genderCombo.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        genderCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        classComboDelete.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        classComboDelete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "11", "12" }));
        classComboDelete.setAlignmentX(0.0F);
        classComboDelete.setAlignmentY(0.0F);

        addButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        addButton.setText("Add Student");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        deleteButton.setText("Delete Student");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        addDelLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        addDelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addDelLabel.setText("Add/Delete Students");
        addDelLabel.setAlignmentY(0.0F);

        javax.swing.GroupLayout panelAddDelLayout = new javax.swing.GroupLayout(panelAddDel);
        panelAddDel.setLayout(panelAddDelLayout);
        panelAddDelLayout.setHorizontalGroup(
            panelAddDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddDelLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(panelAddDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addStudentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAddDelLayout.createSequentialGroup()
                        .addComponent(classLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(classComboAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAddDelLayout.createSequentialGroup()
                        .addComponent(rollNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(rollNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAddDelLayout.createSequentialGroup()
                        .addComponent(fnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(fnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAddDelLayout.createSequentialGroup()
                        .addComponent(lnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(lnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dobLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAddDelLayout.createSequentialGroup()
                        .addComponent(genderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(genderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAddDelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(addButton)))
                .addGap(30, 30, 30)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(panelAddDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteStudentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAddDelLayout.createSequentialGroup()
                        .addComponent(deleteClassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(classComboDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(deleteRollNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAddDelLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAddDelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(deleteButton)))
                .addGap(71, 71, 71)
                .addComponent(filler3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelAddDelLayout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(dobField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelAddDelLayout.createSequentialGroup()
                .addGap(680, 680, 680)
                .addComponent(deleteRollNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(addDelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 893, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelAddDelLayout.setVerticalGroup(
            panelAddDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddDelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(addStudentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(panelAddDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classComboAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(panelAddDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rollNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rollNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(panelAddDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(panelAddDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(dobLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(panelAddDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(genderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelAddDelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelAddDelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(deleteStudentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(panelAddDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteClassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classComboDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(deleteRollNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelAddDelLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(filler3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelAddDelLayout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(dobField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelAddDelLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(deleteRollNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(addDelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        mainPanel.add(panelAddDel, "panelAddDel");

        editRollNoLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        editRollNoLabel.setText("Roll no.");

        editFnameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        editFnameLabel.setText("First Name");

        editLnameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        editLnameLabel.setText("Last Name");

        editDobLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        editDobLabel.setText("DOB (YYYY-MM-DD)");

        editGenderLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        editGenderLabel.setText("Gender");

        editRollNoField.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        editRollNoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editRollNoFieldActionPerformed(evt);
            }
        });

        editFnameField.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        editLnameField.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        editLnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editLnameFieldActionPerformed(evt);
            }
        });

        editDobField.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        editDobField.setToolTipText("");

        editGenderCombo.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        editGenderCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        editClassCombo.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        editClassCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "11", "12" }));

        updateButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        updateButton.setText("Update Student");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        editLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        editLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editLabel.setText("Edit Student");
        editLabel.setAlignmentY(0.0F);

        editClassLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        editClassLabel1.setText("Class");

        requiredLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        requiredLabel2.setText("(Required)");

        requiredLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        requiredLabel1.setText("(Required)");

        javax.swing.GroupLayout panelEditLayout = new javax.swing.GroupLayout(panelEdit);
        panelEdit.setLayout(panelEditLayout);
        panelEditLayout.setHorizontalGroup(
            panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 893, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(panelEditLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(requiredLabel1)
                .addGap(17, 17, 17)
                .addComponent(editClassLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160)
                .addComponent(editClassCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelEditLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(requiredLabel2)
                .addGap(17, 17, 17)
                .addComponent(editRollNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160)
                .addComponent(editRollNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelEditLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(editFnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160)
                .addComponent(editFnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelEditLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(editLnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160)
                .addComponent(editLnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelEditLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(editDobLabel)
                .addGap(132, 132, 132)
                .addComponent(editDobField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelEditLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(editGenderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160)
                .addComponent(editGenderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelEditLayout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelEditLayout.setVerticalGroup(
            panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditLayout.createSequentialGroup()
                .addComponent(editLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(requiredLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editClassLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editClassCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(requiredLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editRollNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editRollNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editFnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editFnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editLnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editLnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editDobLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editDobField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editGenderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editGenderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainPanel.add(panelEdit, "panelEdit");

        jbtPanelStudents.setText("View all Students");
        jbtPanelStudents.setAlignmentY(0.0F);
        jbtPanelStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPanelStudentsActionPerformed(evt);
            }
        });

        jbtPanelAddDel.setText("Add/Delete Student");
        jbtPanelAddDel.setAlignmentY(0.0F);
        jbtPanelAddDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPanelAddDelActionPerformed(evt);
            }
        });

        jbtPanelEdit.setText("Edit Student");
        jbtPanelEdit.setAlignmentY(0.0F);
        jbtPanelEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPanelEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(206, Short.MAX_VALUE)
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(206, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtPanelStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtPanelAddDel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtPanelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 884, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(title)
                .addGap(15, 15, 15)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtPanelStudents, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtPanelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtPanelAddDel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtPanelStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPanelStudentsActionPerformed
       CardLayout card = (CardLayout)mainPanel.getLayout();
       card.show(mainPanel, "panelStudents");
    }//GEN-LAST:event_jbtPanelStudentsActionPerformed

    private void jbtPanelAddDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPanelAddDelActionPerformed
       CardLayout card = (CardLayout)mainPanel.getLayout();
       card.show(mainPanel, "panelAddDel");
    }//GEN-LAST:event_jbtPanelAddDelActionPerformed

    private void jbtPanelEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPanelEditActionPerformed
       CardLayout card = (CardLayout)mainPanel.getLayout();
       card.show(mainPanel, "panelEdit");
    }//GEN-LAST:event_jbtPanelEditActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        searchField.setText("");
        filterCombo.setSelectedIndex(0);
        sorter.setRowFilter(null);
    }//GEN-LAST:event_clearButtonActionPerformed

    private void filterComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterComboActionPerformed
        performFilter();
    }//GEN-LAST:event_filterComboActionPerformed

    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
        performFilter();
    }//GEN-LAST:event_searchFieldKeyReleased

    private void editRollNoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editRollNoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editRollNoFieldActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        String classNo = (String) editClassCombo.getSelectedItem();
        String rollNo = editRollNoField.getText().trim();

        // Class and Roll No are mandatory
        if (rollNo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Class and Roll No are required!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Get values (can be empty)
        String fname = editFnameField.getText().trim();
        String lname = editLnameField.getText().trim();
        String dob = editDobField.getText().trim();
        String gender = (String) editGenderCombo.getSelectedItem();

        // Validate date format if provided
        if (!dob.isEmpty() && !dob.matches("\\d{4}-\\d{2}-\\d{2}")) {
            JOptionPane.showMessageDialog(this, "Invalid date format! Use YYYY-MM-DD", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        updateStudent(classNo, rollNo, fname, lname, dob, gender);

        // Clear fields after update
        editRollNoField.setText("");
        editFnameField.setText("");
        editLnameField.setText("");
        editDobField.setText("");
        editClassCombo.setSelectedIndex(0);
        editGenderCombo.setSelectedIndex(0);
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        String classNo = (String) classComboDelete.getSelectedItem();
        String rollNo = deleteRollNoField.getText().trim();

        if (rollNo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Roll No!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (JOptionPane.showConfirmDialog(this, "Are you sure you want to delete student with Roll No " + rollNo + " from Class " + classNo + "?",
            "Confirm Delete", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        deleteStudent(classNo, rollNo);
        deleteRollNoField.setText("");
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String classNo = (String) classComboAdd.getSelectedItem();
        String rollNo = rollNoField.getText().trim();
        String fname = fnameField.getText().trim();
        String lname = lnameField.getText().trim();
        String dob = dobField.getText().trim();
        String gender = (String) genderCombo.getSelectedItem();

        if (rollNo.isEmpty() || fname.isEmpty() || lname.isEmpty() || dob.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all fields!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!dob.matches("\\d{4}-\\d{2}-\\d{2}")) {
            JOptionPane.showMessageDialog(this, "Invalid date format! Use YYYY-MM-DD", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        addStudent(classNo, rollNo, fname, lname, dob, gender);

        rollNoField.setText(""); fnameField.setText(""); lnameField.setText(""); dobField.setText("");
        classComboAdd.setSelectedIndex(0); genderCombo.setSelectedIndex(0);
    }//GEN-LAST:event_addButtonActionPerformed

    private void rollNoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollNoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rollNoFieldActionPerformed

    private void editLnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editLnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editLnameFieldActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new main().setVisible(true));
    }
    
    private void setupTableSorter() {
        sorter = new TableRowSorter<>(tableModel);
        studentsTable.setRowSorter(sorter);
    }

    private void performFilter() {
        String searchText = searchField.getText().trim();
        String selectedClass = (String) filterCombo.getSelectedItem();

        java.util.List<RowFilter<Object, Object>> filters = new ArrayList<>();

        if (!searchText.isEmpty()) {
            try {
                filters.add(RowFilter.regexFilter("(?i)" + searchText));
            } catch (java.util.regex.PatternSyntaxException ignored) {}
        }

        if (!"All".equals(selectedClass)) {
            filters.add(RowFilter.regexFilter("^" + selectedClass + "$", 0));
        }

        sorter.setRowFilter(filters.isEmpty() ? null : filters.size() == 1 ? filters.get(0) : RowFilter.andFilter(filters));
    }
    
    private void loadStudentData() {
        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/students", "root", "verysecure");
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT * FROM student")) {

            while (rs.next()) {
                tableModel.addRow(new String[]{
                    rs.getString("class"),
                    rs.getString("roll_no"),
                    rs.getString("first_name"),
                    rs.getString("last_name"),
                    rs.getString("date_of_birth"),
                    rs.getString("gender")
                });
            }
        } catch (Exception e) {
            logger.log(java.util.logging.Level.SEVERE, "Error loading student data", e);
            JOptionPane.showMessageDialog(this, 
                "Error loading student data: " + e.getMessage(), 
                "Database Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void addStudent(String classNo, String rollNo, String fname, String lname, String dob, String gender) {
        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/students", "root", "verysecure")) {
            String checkQuery = "SELECT * FROM student WHERE class = ? AND roll_no = ?";
            try (PreparedStatement checkStmt = conn.prepareStatement(checkQuery)) {
                checkStmt.setString(1, classNo);
                checkStmt.setString(2, rollNo);
                try (ResultSet rs = checkStmt.executeQuery()) {
                    if (rs.next()) {
                        JOptionPane.showMessageDialog(this, 
                            "Student with Roll No " + rollNo + " already exists in Class " + classNo + "!", 
                            "Duplicate Entry", 
                            JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                }
            }

            String insertQuery = "INSERT INTO student (class, roll_no, first_name, last_name, date_of_birth, gender) VALUES (?, ?, ?, ?, ?, ?)";
            try (PreparedStatement insertStmt = conn.prepareStatement(insertQuery)) {
                insertStmt.setString(1, classNo);
                insertStmt.setString(2, rollNo);
                insertStmt.setString(3, fname);
                insertStmt.setString(4, lname);
                insertStmt.setString(5, dob);
                insertStmt.setString(6, gender);

                int rowsInserted = insertStmt.executeUpdate();

                if (rowsInserted > 0) {
                    tableModel.addRow(new String[]{classNo, rollNo, fname, lname, dob, gender});
                    JOptionPane.showMessageDialog(this, 
                        "Student added successfully!", 
                        "Success", 
                        JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (Exception e) {
            logger.log(java.util.logging.Level.SEVERE, "Error adding student", e);
            JOptionPane.showMessageDialog(this, 
                "Error adding student: " + e.getMessage(), 
                "Database Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }

    private void deleteStudent(String classNo, String rollNo) {
        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/students", "root", "verysecure")) {
            String deleteQuery = "DELETE FROM student WHERE class = ? AND roll_no = ?";
            try (PreparedStatement deleteStmt = conn.prepareStatement(deleteQuery)) {
                deleteStmt.setString(1, classNo);
                deleteStmt.setString(2, rollNo);

                int rowsDeleted = deleteStmt.executeUpdate();

                if (rowsDeleted > 0) {
                    for (int i = 0; i < tableModel.getRowCount(); i++) {
                        if (tableModel.getValueAt(i, 0).equals(classNo) && 
                            tableModel.getValueAt(i, 1).equals(rollNo)) {
                            tableModel.removeRow(i);
                            break;
                        }
                    }
                    JOptionPane.showMessageDialog(this, 
                        "Student deleted successfully!", 
                        "Success", 
                        JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, 
                        "Student not found!", 
                        "Error", 
                        JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception e) {
            logger.log(java.util.logging.Level.SEVERE, "Error deleting student", e);
            JOptionPane.showMessageDialog(this, 
                "Error deleting student: " + e.getMessage(), 
                "Database Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void updateStudent(String classNo, String rollNo, String fname, String lname, String dob, String gender) {
    try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/students", "root", "verysecure")) {
        // Check if student exists
        String checkQuery = "SELECT * FROM student WHERE class = ? AND roll_no = ?";
        try (PreparedStatement checkStmt = conn.prepareStatement(checkQuery)) {
            checkStmt.setString(1, classNo);
            checkStmt.setString(2, rollNo);
            try (ResultSet rs = checkStmt.executeQuery()) {
                if (!rs.next()) {
                    JOptionPane.showMessageDialog(this, 
                        "Student with Roll No " + rollNo + " not found in Class " + classNo + "!", 
                        "Not Found", 
                        JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        }

        // Build dynamic UPDATE query based on filled fields
        java.util.List<String> updates = new ArrayList<>(), values = new ArrayList<>();
        if (!fname.isEmpty()) { updates.add("first_name = ?"); values.add(fname); }
        if (!lname.isEmpty()) { updates.add("last_name = ?"); values.add(lname); }
        if (!dob.isEmpty()) { updates.add("date_of_birth = ?"); values.add(dob); }
        if (gender != null && !gender.isEmpty()) { updates.add("gender = ?"); values.add(gender); }

        if (updates.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Please fill at least one field to update!", 
                "No Changes", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        String updateQuery = "UPDATE student SET " + String.join(", ", updates) + " WHERE class = ? AND roll_no = ?";
        try (PreparedStatement updateStmt = conn.prepareStatement(updateQuery)) {
            int paramIndex = 1;
            for (String value : values) updateStmt.setString(paramIndex++, value);
            updateStmt.setString(paramIndex++, classNo);
            updateStmt.setString(paramIndex, rollNo);

            int rowsUpdated = updateStmt.executeUpdate();

            if (rowsUpdated > 0) {
                // Update table model with new values
                for (int i = 0; i < tableModel.getRowCount(); i++) {
                    if (tableModel.getValueAt(i, 0).equals(classNo) && tableModel.getValueAt(i, 1).equals(rollNo)) {
                        if (!fname.isEmpty()) tableModel.setValueAt(fname, i, 2);
                        if (!lname.isEmpty()) tableModel.setValueAt(lname, i, 3);
                        if (!dob.isEmpty()) tableModel.setValueAt(dob, i, 4);
                        if (gender != null && !gender.isEmpty()) tableModel.setValueAt(gender, i, 5);
                        break;
                    }
                }

                JOptionPane.showMessageDialog(this, 
                    "Student updated successfully!", 
                    "Success", 
                    JOptionPane.INFORMATION_MESSAGE);
            }
        }
    } catch (Exception e) {
        logger.log(java.util.logging.Level.SEVERE, "Error updating student", e);
        JOptionPane.showMessageDialog(this, 
            "Error updating student: " + e.getMessage(), 
            "Database Error", 
            JOptionPane.ERROR_MESSAGE);
    }
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel addDelLabel;
    private javax.swing.JLabel addStudentLabel;
    private javax.swing.JLabel allLabel;
    private javax.swing.JComboBox<String> classComboAdd;
    private javax.swing.JComboBox<String> classComboDelete;
    private javax.swing.JLabel classLabel;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel deleteClassLabel;
    private javax.swing.JTextField deleteRollNoField;
    private javax.swing.JLabel deleteRollNoLabel;
    private javax.swing.JLabel deleteStudentLabel;
    private javax.swing.JTextField dobField;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JComboBox<String> editClassCombo;
    private javax.swing.JLabel editClassLabel1;
    private javax.swing.JTextField editDobField;
    private javax.swing.JLabel editDobLabel;
    private javax.swing.JTextField editFnameField;
    private javax.swing.JLabel editFnameLabel;
    private javax.swing.JComboBox<String> editGenderCombo;
    private javax.swing.JLabel editGenderLabel;
    private javax.swing.JLabel editLabel;
    private javax.swing.JTextField editLnameField;
    private javax.swing.JLabel editLnameLabel;
    private javax.swing.JTextField editRollNoField;
    private javax.swing.JLabel editRollNoLabel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JComboBox<String> filterCombo;
    private javax.swing.JLabel filterLabel;
    private javax.swing.JTextField fnameField;
    private javax.swing.JLabel fnameLabel;
    private javax.swing.JComboBox<String> genderCombo;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbtPanelAddDel;
    private javax.swing.JButton jbtPanelEdit;
    private javax.swing.JButton jbtPanelStudents;
    private javax.swing.JTextField lnameField;
    private javax.swing.JLabel lnameLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelAddDel;
    private javax.swing.JPanel panelEdit;
    private javax.swing.JPanel panelStudents;
    private javax.swing.JLabel requiredLabel1;
    private javax.swing.JLabel requiredLabel2;
    private javax.swing.JTextField rollNoField;
    private javax.swing.JLabel rollNoLabel;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JTable studentsTable;
    private javax.swing.JLabel title;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
